services:
  postgres:
    image: postgres:17.2
    ports:
      - "5432:5432"
    volumes:
      - "./postgres/data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: analyticsUser
      POSTGRES_PASSWORD: SQLisAwesome!
      POSTGRES_DB: analytics
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U analyticsUser -d analytics"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  default:
    name: my-data-network
